/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.adventuresgalore.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.core.registries.Registries;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraft.core.particles.ParticleType;

import net.mcreator.adventuresgalore.AdventuresGaloreMod;

public class AdventuresGaloreModParticleTypes {
	public static final DeferredRegister<ParticleType<?>> REGISTRY = DeferredRegister.create(Registries.PARTICLE_TYPE, AdventuresGaloreMod.MODID);
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> ONE_BLUNT_DAMAGE = REGISTRY.register("one_blunt_damage", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> TWO_BLUNT_DAMAGE = REGISTRY.register("two_blunt_damage", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> THREE_BLUNT_DAMAGE = REGISTRY.register("three_blunt_damage", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> FOUR_BLUNT_DAMAGE = REGISTRY.register("four_blunt_damage", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> FIVE_BLUNT_DAMAGE = REGISTRY.register("five_blunt_damage", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> SIX_BLUNT_DAMAGE = REGISTRY.register("six_blunt_damage", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> SEVEN_BLUNT_DAMAGE = REGISTRY.register("seven_blunt_damage", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> EIGHT_BLUNT_DAMAGE = REGISTRY.register("eight_blunt_damage", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> NINE_BLUNT_DAMAGE = REGISTRY.register("nine_blunt_damage", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_1 = REGISTRY.register("vanilla_damage_1", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_2 = REGISTRY.register("vanilla_damage_2", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_3 = REGISTRY.register("vanilla_damage_3", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_4 = REGISTRY.register("vanilla_damage_4", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_5 = REGISTRY.register("vanilla_damage_5", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_6 = REGISTRY.register("vanilla_damage_6", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_7 = REGISTRY.register("vanilla_damage_7", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_8 = REGISTRY.register("vanilla_damage_8", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_9 = REGISTRY.register("vanilla_damage_9", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_10 = REGISTRY.register("vanilla_damage_10", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_11 = REGISTRY.register("vanilla_damage_11", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_12 = REGISTRY.register("vanilla_damage_12", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_13 = REGISTRY.register("vanilla_damage_13", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_14 = REGISTRY.register("vanilla_damage_14", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_15 = REGISTRY.register("vanilla_damage_15", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_16 = REGISTRY.register("vanilla_damage_16", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_17 = REGISTRY.register("vanilla_damage_17", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_18 = REGISTRY.register("vanilla_damage_18", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_19 = REGISTRY.register("vanilla_damage_19", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_20 = REGISTRY.register("vanilla_damage_20", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_21 = REGISTRY.register("vanilla_damage_21", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_22 = REGISTRY.register("vanilla_damage_22", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_23 = REGISTRY.register("vanilla_damage_23", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_24 = REGISTRY.register("vanilla_damage_24", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_25 = REGISTRY.register("vanilla_damage_25", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_26 = REGISTRY.register("vanilla_damage_26", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_27 = REGISTRY.register("vanilla_damage_27", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_28 = REGISTRY.register("vanilla_damage_28", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_29 = REGISTRY.register("vanilla_damage_29", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_30 = REGISTRY.register("vanilla_damage_30", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_31 = REGISTRY.register("vanilla_damage_31", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_32 = REGISTRY.register("vanilla_damage_32", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_33 = REGISTRY.register("vanilla_damage_33", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_34 = REGISTRY.register("vanilla_damage_34", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_35 = REGISTRY.register("vanilla_damage_35", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_36 = REGISTRY.register("vanilla_damage_36", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_37 = REGISTRY.register("vanilla_damage_37", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_38 = REGISTRY.register("vanilla_damage_38", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_39 = REGISTRY.register("vanilla_damage_39", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_40 = REGISTRY.register("vanilla_damage_40", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_41 = REGISTRY.register("vanilla_damage_41", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_42 = REGISTRY.register("vanilla_damage_42", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_43 = REGISTRY.register("vanilla_damage_43", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_44 = REGISTRY.register("vanilla_damage_44", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_45 = REGISTRY.register("vanilla_damage_45", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_46 = REGISTRY.register("vanilla_damage_46", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_47 = REGISTRY.register("vanilla_damage_47", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_48 = REGISTRY.register("vanilla_damage_48", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_49 = REGISTRY.register("vanilla_damage_49", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_50 = REGISTRY.register("vanilla_damage_50", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_51 = REGISTRY.register("vanilla_damage_51", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_52 = REGISTRY.register("vanilla_damage_52", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_53 = REGISTRY.register("vanilla_damage_53", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_54 = REGISTRY.register("vanilla_damage_54", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_55 = REGISTRY.register("vanilla_damage_55", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_56 = REGISTRY.register("vanilla_damage_56", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_57 = REGISTRY.register("vanilla_damage_57", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_58 = REGISTRY.register("vanilla_damage_58", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_59 = REGISTRY.register("vanilla_damage_59", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_60 = REGISTRY.register("vanilla_damage_60", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_61 = REGISTRY.register("vanilla_damage_61", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_62 = REGISTRY.register("vanilla_damage_62", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_63 = REGISTRY.register("vanilla_damage_63", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_64 = REGISTRY.register("vanilla_damage_64", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_65 = REGISTRY.register("vanilla_damage_65", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_66 = REGISTRY.register("vanilla_damage_66", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_67 = REGISTRY.register("vanilla_damage_67", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_68 = REGISTRY.register("vanilla_damage_68", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_69 = REGISTRY.register("vanilla_damage_69", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_70 = REGISTRY.register("vanilla_damage_70", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_71 = REGISTRY.register("vanilla_damage_71", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_72 = REGISTRY.register("vanilla_damage_72", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_73 = REGISTRY.register("vanilla_damage_73", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_74 = REGISTRY.register("vanilla_damage_74", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_75 = REGISTRY.register("vanilla_damage_75", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_76 = REGISTRY.register("vanilla_damage_76", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_77 = REGISTRY.register("vanilla_damage_77", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_78 = REGISTRY.register("vanilla_damage_78", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_79 = REGISTRY.register("vanilla_damage_79", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_80 = REGISTRY.register("vanilla_damage_80", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_81 = REGISTRY.register("vanilla_damage_81", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_82 = REGISTRY.register("vanilla_damage_82", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_83 = REGISTRY.register("vanilla_damage_83", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_84 = REGISTRY.register("vanilla_damage_84", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_85 = REGISTRY.register("vanilla_damage_85", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_86 = REGISTRY.register("vanilla_damage_86", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_87 = REGISTRY.register("vanilla_damage_87", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_88 = REGISTRY.register("vanilla_damage_88", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_89 = REGISTRY.register("vanilla_damage_89", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_90 = REGISTRY.register("vanilla_damage_90", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_91 = REGISTRY.register("vanilla_damage_91", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_92 = REGISTRY.register("vanilla_damage_92", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_93 = REGISTRY.register("vanilla_damage_93", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_94 = REGISTRY.register("vanilla_damage_94", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_95 = REGISTRY.register("vanilla_damage_95", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_96 = REGISTRY.register("vanilla_damage_96", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_97 = REGISTRY.register("vanilla_damage_97", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_98 = REGISTRY.register("vanilla_damage_98", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_99 = REGISTRY.register("vanilla_damage_99", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_100 = REGISTRY.register("vanilla_damage_100", () -> new SimpleParticleType(true));
	public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VANILLA_DAMAGE_100PLUS = REGISTRY.register("vanilla_damage_100plus", () -> new SimpleParticleType(true));
}